name: generate_public_json
on:
  workflow_dispatch:
jobs:
  generate_json:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v3
      with:
        repository: CDLUC3/naan_reg_priv
        token: ${{ secrets.NAAN_REG_PRIV_PAT }}
        path: naan_reg_priv
        
